"""empty message

Revision ID: 8e59d4e1103a
Revises: ac91ea86c7f3
Create Date: 2024-07-13 20:16:53.439597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e59d4e1103a'
down_revision = 'ac91ea86c7f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=225),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.String(length=225),
               type_=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###
